FROM node:alpine
EXPOSE 8080
RUN mkdir -p /app/public /app/src
WORKDIR /app
COPY tsconfig.json /app/tsconfig.json
COPY eslint.config.mjs /app/eslint.config.mjs
COPY package.json /app/package.json
COPY .prettierrc /app/.prettierrc
COPY .prettierignore /app/.prettierignore
COPY package-lock.json /app/package-lock.json
RUN npm install
CMD ["npm", "run", "start"]