FROM node:alpine
RUN mkdir -p /app/config /app/src
WORKDIR /app
COPY src/ /app/src
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
COPY tsconfig.json /app/tsconfig.json
COPY webpack.config.js /app/webpack.config.js
COPY .env /app/.env
RUN npm install
CMD ["npm", "run", "start"]